export const EMPLOYEE_AUTORIZATION_SUCCESS = 'EMPLOYEE_AUTORIZATION_SUCCESS';
export const EMPLOYEE_AUTHORIZATION_FAILED = 'EMPLOYEE_AUTHORIZATION_FAILED';
export const RESET_ACTIVE_MENU = 'RESET_ACTIVE_MENU';
export const SET_ACTIVE_MENU = 'SET_ACTIVE_MENU';
export const EMPLOYEE_LOGOUT = 'EMPLOYEE_LOGOUT';
export const ACTIVE_ID_SET = 'ACTIVE_ID_SET';
export const UPDATE_PROCEDURE_TYPE_MODAL_WINDOW_STATE =
  'UPDATE_PROCEDURE_TYPE_MODAL_WINDOW_STATE';
export const CREATE_PROCEDURE_TYPE_MODAL_WINDOW_STATE =
  'CREATE_PROCEDURE_TYPE_MODAL_WINDOW_STATE';
export const UPDATE_MODAL_WINDOW_STATE = 'UPDATE_MODAL_WINDOW_STATE';
export const CREATE_MODAL_WINDOW_STATE = 'CREATE_MODAL_WINDOW_STATE';
export const LOGIN_MODAL_WINDOW_STATE = 'LOGIN_MODAL_WINDOW_STATE';
export const EDIT_STATE = 'EDIT_STATE';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const FETCH_TABLE_DATA_SUCCESS = 'FETCH_TABLE_DATA_SUCCESS';
export const SINGLE_RECORD_FETCH_DATA_SUCCESS =
  'SINGLE_RECORD_FETCH_DATA_SUCCESS';

//FOR ORDER CREATION
export const PROCEDURE_FETCH_DATA_SUCCESS = 'PROCEDURE_FETCH_DATA_SUCCESS';
export const EMPLOYEE_FETCH_DATA_SUCCESS = 'EMPLOYEE_FETCH_DATA_SUCCESS';
export const SCHEDULE_FETCH_DATA_SUCCESS = 'SCHEDULE_FETCH_DATA_SUCCESS';
export const SET_ACTIVE_PROCEDURE = 'SET_ACTIVE_PROCEDURE';
export const SET_ACTIVE_PROCEDURE_TYPE = 'SET_ACTIVE_PROCEDURE_TYPE';
export const SET_ACTIVE_DATE = 'SET_ACTIVE_DATE';
export const SET_ACTIVE_TIME = 'SET_ACTIVE_TIME';
export const SET_ACTIVE_EMPLOYEE = 'SET_ACTIVE_EMPLOYEE';
export const SET_ACTIVE_CLIENT = 'SET_ACTIVE_CLIENT';
export const RESET_SELECTED_VALUES = 'RESET_SELECTED_VALUES';
export const SET_SELECTED_VALUE = 'SET_SELECTED_VALUE';
export const RESET_SINGLE_SELECTED_VALUE = 'RESET_SINGLE_SELECTED_VALUE';

//FOR ORDER CREATION (states of ordering stages)
export const SET_BOOKING_STATUS = 'SET_BOOKING_STATUS';
export const REDIRECT_TO_ORDERING = 'REDIRECT_TO_ORDERING';
export const SET_ORDER_CREATION_STATUS = 'SET_ORDER_CREATION_STATUS';

//FOR PROFILE IMAGE GETTING

export const FETCH_PROFILE_PHOTO_SUCCESS = 'FETCH_PROFILE_PHOTO_SUCCESS';
export const RESET_SINGLE_DATA = 'RESET_SINGLE_DATA';

// FOR PROCEDURE TYPE PHOTO GETTING

export const FETCH_PROCEDURE_TYPE_PHOTO_SUCCESS =
  'FETCH_PROCEDURE_TYPE_PHOTO_SUCCESS';

// FOR MEDIAFILES_TYPE_SETTING

export const SET_ACTIVE_MEDIA_TYPE = 'SET_ACTIVE_MEDIA_TYPE';

// FOR FEEDBACKS CHECKING

export const SET_NEW_FEEDBACKS_STATE = 'SET_NEW_FEEDBACKS_STATE';

// FOR NEW ORDERS CHECKING

export const SET_NEW_ORDERS_STATE = 'SET_NEW_ORDERS_STATE';
